[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
Foresight = "c6e1034d-1844-4b96-abf2-c5824a5aa8c3"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
TimeseriesMakie = "5e3e9a77-7bbf-480c-931c-0802e2453f5a"
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"
